name: Build and Push docker image

on: ["push"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: "â¬‡ï¸ Checkout code"
        uses: actions/checkout@v4

      - name: "ğŸ˜ Log in to Github Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "ğŸ’­ Determine docker image tag"
        run: |
          readonly is_tag=${{ startsWith(github.ref, 'refs/tags/') }}

          if [ "$is_tag" = "true" ]; then
            readonly tag=${{ github.ref#refs/tags/ }}
            echo "We are in a TAG event, using tag as image tag..."
          else
            readonly tag=${GITHUB_SHA::7}
          fi

          echo "The image tag will be: ${tag}"
          echo "IMAGE_TAG=${tag}" >> $GITHUB_ENV

      - name: "ğŸ‘· Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "ğŸ”¨ & â¬†ï¸ Build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
